### ISSUE TITLE
Check if item already exists on scan

### ISSUE THREAD

**Issue by AdamVig** [stockpile-co/app#356] opened 2017-08-21 03:01 UTC
As a Stockpile user,
I want to know if the barcode of the item I am attempting to add already exists in the inventory before I enter information about the item
so that I can save time when I accidentally scan the same barcode twice.

Current behavior:
1. Tap "+" to add item.
2. Scan a barcode that already exists.
3. Enter Brand, Model, and Category.
4. Tap "Save."
5. Toast appears: "Already exists."
6. App remains on "Add Item" view, even though there is no way the user can remediate the conflict within that view.

Desired behavior:
1. Tap "+" to add item.
2. Scan a barcode that already exists.
3. Barcode scanner exits back to Inventory view, toast appears: "Already exists."

Note that in the desired behavior, the user isn't even brought to the "Add Item" view if the item already exists.

It could be useful to bring the user to the item that already exists, or show them a preview of what it is, so they can quickly discern why there is a conflict.

**Comment by emroussel** [comment] 2017-08-21 16:55
Duplicate of #255

**Closed by emroussel** 2017-08-21 16:55 UTC
Labels: enhancement, ux
